import { QuestionLevel } from '@/types/QuestionLevel';
import { QuestionObj } from '@/types/QuestionObj';

/**
 * 問題一覧
 *
 * ※クラス名とimport名を同一にするためlintオプションでnamespaceの使用を許可する
 */
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace QuestionConst {
  /** 問題一覧 */
  export const QuestionList: { [key in QuestionLevel]: QuestionObj[] } = {
    // ------- 漢検3級 ------
    level1: [
      {
        kanji: '試行錯誤',
        kana: 'しこうさくご',
        explanation: '試みては失敗し、その度に新しい方法を試すこと',
      },
      {
        kanji: '独自性',
        kana: 'どくじせい',
        explanation: '他とは異なり、独自の特長や個性を持っていること',
      },
      {
        kanji: '悪循環',
        kana: 'あくじゅんかん',
        explanation: '悪い状態が続き、悪化の一途をたどること',
      },
      {
        kanji: '絶滅危惧種',
        kana: 'ぜつめつきぐしゅ',
        explanation: '絶滅の危機に瀕している生物の種',
      },
      {
        kanji: '一網打尽',
        kana: 'いちもうだじん',
        explanation: '一度に全てを捕らえること',
      },
      {
        kanji: '倹約生活',
        kana: 'けんやくせいかつ',
        explanation: '節約し質素な生活を送ること',
      },
      {
        kanji: '有無を言わさぬ',
        kana: 'うむをいわさぬ',
        explanation: '相手に選択の余地を与えず、無条件で行動させること',
      },
      {
        kanji: '大同小異',
        kana: 'だいどうしょうい',
        explanation: '大きな違いはなく、細かい差異があること',
      },
      {
        kanji: '偉大',
        kana: 'いだい',
        explanation: '非常に優れていて素晴らしいこと',
      },
      {
        kanji: '継続的',
        kana: 'けいぞくてき',
        explanation: '一定の間隔をおいて続くこと',
      },
      {
        kanji: '機敏',
        kana: 'きびん',
        explanation: '動作が素早く、敏捷であること',
      },
      {
        kanji: '一意専心',
        kana: 'いちいせんしん',
        explanation: '一つの目標や事に心を集中すること',
      },
      {
        kanji: '発奮',
        kana: 'はっぷん',
        explanation: '気合や意気込みを奮い立たせること',
      },
      {
        kanji: '根深い',
        kana: 'ねぶかい',
        explanation: '問題や影響が深く広がっていること',
      },
      {
        kanji: '危機一髪',
        kana: 'ききいっぱつ',
        explanation: '非常に危険な状況から辛くも脱すること',
      },
      {
        kanji: '無欲',
        kana: 'むよく',
        explanation: '物事に執着せず欲望がないこと',
      },
      {
        kanji: '鮮烈',
        kana: 'せんれつ',
        explanation: '非常に強烈で印象的なこと',
      },
      {
        kanji: '透明',
        kana: 'とうめい',
        explanation: '中身や本質がはっきり見えること',
      },
      {
        kanji: '悠々',
        kana: 'ゆうゆう',
        explanation: 'のんびりとした様子、余裕があること',
      },
      {
        kanji: '労力',
        kana: 'ろうりょく',
        explanation: '仕事や活動にかかる努力やエネルギー',
      },
      {
        kanji: '潔癖',
        kana: 'けっぺき',
        explanation: '清潔であること、物事に対して妥協しないこと',
      },
      {
        kanji: '奮発',
        kana: 'ふんぱつ',
        explanation: '力を込めて努力すること',
      },
      {
        kanji: '混同',
        kana: 'こんどう',
        explanation: '異なるものを混ぜて区別がつかなくなること',
      },
      {
        kanji: '宿命',
        kana: 'しゅくめい',
        explanation: '生まれつき持っている運命や定め',
      },
      {
        kanji: '独占',
        kana: 'どくせん',
        explanation: '他と共有せず、独り占めすること',
      },
      {
        kanji: '不屈',
        kana: 'ふくつ',
        explanation: '逆境に負けずに堂々と立ち向かうこと',
      },
      {
        kanji: '強烈',
        kana: 'きょうれつ',
        explanation: '非常に強い印象や効果を持つこと',
      },
      {
        kanji: '懐疑的',
        kana: 'かいぎてき',
        explanation: '疑念や不信感を抱いていること',
      },
      {
        kanji: '逆転',
        kana: 'ぎゃくてん',
        explanation: '予想や状況が逆になること',
      },
      {
        kanji: '主観的',
        kana: 'しゅかんてき',
        explanation: '自分の感じ方や意見に基づいたこと',
      },
      {
        kanji: '快挙',
        kana: 'かいきょ',
        explanation: '驚くべき成就や成績の達成',
      },
      {
        kanji: '平凡',
        kana: 'へいぼん',
        explanation: '普通であり特別なことがない様子',
      },
      {
        kanji: '合理的',
        kana: 'ごうりてき',
        explanation: '理性的で論理的なこと',
      },
      {
        kanji: '適度',
        kana: 'てきど',
        explanation: 'ちょうど良い程度や度合い',
      },
      {
        kanji: '抑制',
        kana: 'よくせい',
        explanation: '抑え込むこと、抑えること',
      },
      {
        kanji: '矛盾',
        kana: 'むじゅん',
        explanation: '自相矛盾していること、食い違っていること',
      },
      {
        kanji: '疑惑',
        kana: 'ぎわく',
        explanation: '疑いや疑念があること',
      },
      {
        kanji: '衝撃',
        kana: 'しょうげき',
        explanation: '強い刺激や影響を与えること',
      },
      {
        kanji: '模範',
        kana: 'もはん',
        explanation: '他のものの手本や模範となること',
      },
      {
        kanji: '非難',
        kana: 'ひなん',
        explanation: '批判や非難を受けること',
      },
      {
        kanji: '不満',
        kana: 'ふまん',
        explanation: '満足できない感情や考え',
      },
      {
        kanji: '異議',
        kana: 'いぎ',
        explanation: '異論や反対の意見',
      },
      {
        kanji: '希望的観測',
        kana: 'きぼうてきかんそく',
        explanation: '楽観的な予測や見通し',
      },
      {
        kanji: '憤慨',
        kana: 'ふんがい',
        explanation: '激しく怒ること',
      },
      {
        kanji: '懲りる',
        kana: 'こりる',
        explanation: '経験から学び、同じことを繰り返さなくなること',
      },
      {
        kanji: '優勝',
        kana: 'ゆうしょう',
        explanation: '競技で一番優れていること、またはその位置',
      },
      {
        kanji: '欧米',
        kana: 'おうべい',
        explanation: '欧州とアメリカ合衆国を指す',
      },
      {
        kanji: '遂行',
        kana: 'すいこう',
        explanation: '計画や目標を実現するために進めること',
      },
      {
        kanji: '郊外',
        kana: 'こうがい',
        explanation: '都市や市街地から離れた地域',
      },
      {
        kanji: '促進',
        kana: 'そくしん',
        explanation: '進展や発展を促すこと',
      },
      {
        kanji: '鍛錬',
        kana: 'たんれん',
        explanation: '鍛え練ること。特に、体力や技術を鍛えること',
      },
      {
        kanji: '放浪',
        kana: 'ほうろう',
        explanation: '特定の目的や目標なく、ふらふらと歩き回ること',
      },
      {
        kanji: '犠牲',
        kana: 'ぎせい',
        explanation: '自己を犠牲にして他者のためになること',
      },
      {
        kanji: '移籍',
        kana: 'いせき',
        explanation: '職場や所属チームなどを変えて移動すること',
      },
      {
        kanji: '古墳',
        kana: 'こふん',
        explanation: '古代の墓で、特に日本に多く見られる円墳や方墳',
      },
      {
        kanji: '衰退',
        kana: 'すいたい',
        explanation: '勢いや力が衰えて衰えること',
      },
      {
        kanji: '拡充',
        kana: 'かくじゅう',
        explanation: '範囲や内容を広げ、充実させること',
      },
      {
        kanji: '悠久',
        kana: 'ゆうきゅう',
        explanation: '永遠に続くようす。永遠の時を感じさせること',
      },
      {
        kanji: '繁栄',
        kana: 'はんえい',
        explanation: '物事が栄え、豊かで繁盛していること',
      },
      {
        kanji: '継続',
        kana: 'けいぞく',
        explanation: '途切れず続くこと。中断せずに続けること',
      },
      {
        kanji: '漸進',
        kana: 'ぜんしん',
        explanation: '少しずつ進むこと。徐々に進行すること',
      },
      {
        kanji: '勇猛',
        kana: 'ゆうもう',
        explanation: '勇敢で力強く、勇気あるさま',
      },
      {
        kanji: '独立',
        kana: 'どくりつ',
        explanation: '他から独自に立ち上がり、自立すること',
      },
      {
        kanji: '潔白',
        kana: 'けっぱく',
        explanation: '罪などがなく、清らかであること',
      },
      {
        kanji: '雄大',
        kana: 'ゆうだい',
        explanation: '大きく力強いさま。壮大で荘厳な様子',
      },
      {
        kanji: '堅実',
        kana: 'けんじつ',
        explanation: 'しっかりしていて、安定していること',
      },
      {
        kanji: '憂鬱',
        kana: 'ゆううつ',
        explanation: '気分が沈んで暗いさま。抑えきれない悲しみや不安',
      },
      {
        kanji: '優雅',
        kana: 'ゆうが',
        explanation: '上品で気品があり、優れた美しさを持っていること',
      },
      {
        kanji: '健全',
        kana: 'けんぜん',
        explanation: '健康で全体的に良好な状態であること',
      },
      {
        kanji: '奇跡',
        kana: 'きせき',
        explanation: '驚くべき出来事や不可解な出来事',
      },
      {
        kanji: '厳格',
        kana: 'げんかく',
        explanation: '非常に厳しい態度や規律を持っていること',
      },
      {
        kanji: '微妙',
        kana: 'びみょう',
        explanation: '非常に細かく微細で、感覚的に分かりにくいこと',
      },
      {
        kanji: '慈悲',
        kana: 'じひ',
        explanation: '他者に対する深い愛情や思いやり',
      },
      {
        kanji: '漂流',
        kana: 'ひょうりゅう',
        explanation: '流れに身をまかせて移動すること',
      },
      {
        kanji: '謀略',
        kana: 'ぼうりゃく',
        explanation: '策略やたくらみによって他者を欺くこと',
      },
      {
        kanji: '疾走',
        kana: 'しっそう',
        explanation: '非常に速く走り抜けること',
      },
      {
        kanji: '興奮',
        kana: 'こうふん',
        explanation: '興味や感情が高まり、活気づくこと',
      },
      {
        kanji: '細心',
        kana: 'さいしん',
        explanation: '非常に注意深く、細かいことに気を使うさま',
      },
      {
        kanji: '潔い',
        kana: 'いさぎよい',
        explanation: '清らかであり、心がけが純粋であること',
      },
      {
        kanji: '軽蔑',
        kana: 'けいべつ',
        explanation: '相手を軽んじ、見下すこと',
      },
      {
        kanji: '営巣',
        kana: 'えいそう',
        explanation: '鳥が巣を作り、繁殖活動を行うこと',
      },
      {
        kanji: '復習',
        kana: 'ふくしゅう',
        explanation: '学習した内容を復活させ、再び勉強すること',
      },
      {
        kanji: '旺盛',
        kana: 'おうせい',
        explanation: '勢いや活気が非常に盛んであること',
      },
      {
        kanji: '拘泥',
        kana: 'こうでい',
        explanation: 'こだわりすぎて、柔軟性がないこと',
      },
      {
        kanji: '晩餐',
        kana: 'ばんさん',
        explanation: '夜の食事、晩餐会などの正式な夕食',
      },
      {
        kanji: '妥協',
        kana: 'だきょう',
        explanation: 'お互いに譲歩し合い、妥当な合意点を見つけること',
      },
      {
        kanji: '貢献',
        kana: 'こうけん',
        explanation: '力を注いで他者や組織に寄与すること',
      },
      {
        kanji: '懇親',
        kana: 'こんしん',
        explanation: '親しみを深め、打ち解けること',
      },
      {
        kanji: '隔離',
        kana: 'かくり',
        explanation: '他との間に物理的または感情的な障壁を設けること',
      },
      {
        kanji: '訓練',
        kana: 'くんれん',
        explanation: '特定の能力や技術を向上させるための練習や修練',
      },
      {
        kanji: '穏和',
        kana: 'おんわ',
        explanation: '穏やかで温和な様子',
      },
      {
        kanji: '範疇',
        kana: 'はんちゅう',
        explanation: '特定の領域や範囲。分野や区分',
      },
      {
        kanji: '快適',
        kana: 'かいてき',
        explanation: '心地よくて、快い状態であること',
      },
      {
        kanji: '冷酷',
        kana: 'れいこく',
        explanation: '非情で冷たいさま',
      },
      {
        kanji: '模索',
        kana: 'もさく',
        explanation: '手探りで探し求めること。試行錯誤',
      },
      {
        kanji: '創造',
        kana: 'そうぞう',
        explanation: '新しいものを生み出すこと。独創的な発想',
      },
      {
        kanji: '幻想',
        kana: 'げんそう',
        explanation: '実在しないような非現実的なイメージや考え',
      },
      {
        kanji: '雄弁',
        kana: 'ゆうべん',
        explanation: '話し上手で、説得力があること',
      },
      {
        kanji: '契機',
        kana: 'けいき',
        explanation: '出発点やきっかけとなる重要な時点',
      },
      {
        kanji: '蓄積',
        kana: 'ちくせき',
        explanation: '物事がたまって蓄えられること',
      },
      {
        kanji: '倹約',
        kana: 'けんやく',
        explanation: '節約し、無駄を省くこと',
      },
      {
        kanji: '拝借',
        kana: 'はいしゃく',
        explanation: '一時的に借りること。借用すること',
      },
      {
        kanji: '壮絶',
        kana: 'そうぜつ',
        explanation: '非常に激しく壮大で劇的な様子',
      },
      {
        kanji: '悲嘆',
        kana: 'ひたん',
        explanation: '悲しみや失望に打ちひしがれること',
      },
      {
        kanji: '綻び',
        kana: 'ほころび',
        explanation: '織物や関係などが、裂けたり開いたりすること',
      },
      {
        kanji: '憐憫',
        kana: 'れんびん',
        explanation: '相手に対して哀れみや同情を感じること',
      },
      {
        kanji: '逸脱',
        kana: 'いつだつ',
        explanation: '通常の軌道から外れること。本来の方向から外れること',
      },
      {
        kanji: '紆余曲折',
        kana: 'うよきょくせつ',
        explanation: '複雑で曲がりくねった経緯や経過',
      },
      {
        kanji: '躍進',
        kana: 'やくしん',
        explanation: '飛躍的に進展し、発展すること',
      },
      {
        kanji: '錯覚',
        kana: 'さっかく',
        explanation: '実際にはないものを感じたり誤解したりすること',
      },
      {
        kanji: '優柔不断',
        kana: 'ゆうじゅうふだん',
        explanation: '物事を決断できず、迷いがちな様子',
      },
      {
        kanji: '稚拙',
        kana: 'ちせつ',
        explanation: '未熟で幼稚な様子',
      },
      {
        kanji: '遺憾',
        kana: 'いかん',
        explanation: '残念であること。後悔や遺憾の念',
      },
      {
        kanji: '疎遠',
        kana: 'そえん',
        explanation: '疎かにして、遠ざかっていること',
      },
      {
        kanji: '懸念',
        kana: 'けねん',
        explanation: '心配や不安を抱くこと',
      },
      {
        kanji: '妙技',
        kana: 'みょうぎ',
        explanation: '非常に優れた技術や手腕',
      },
      {
        kanji: '瑞々しい',
        kana: 'みずみずしい',
        explanation: '新鮮でみずみずしいさま',
      },
      {
        kanji: '暴露',
        kana: 'ばくろ',
        explanation: '秘密や真実を明らかにすること',
      },
      {
        kanji: '寛容',
        kana: 'かんよう',
        explanation: '他人の違いや間違いを受け入れ、寛大な態度を持つこと',
      },
      {
        kanji: '賑わい',
        kana: 'にぎわい',
        explanation: '賑やかで活気に満ちた様子',
      },
      {
        kanji: '凛々しい',
        kana: 'りりしい',
        explanation: '気品があり、立派で力強いさま',
      },
      {
        kanji: '繁殖',
        kana: 'はんしょく',
        explanation: '生物が増殖し、繁栄すること',
      },
      {
        kanji: '緩和',
        kana: 'かんわ',
        explanation: '状態や緊張が和らぎ、緩んでゆるむこと',
      },
      {
        kanji: '抽象',
        kana: 'ちゅうしょう',
        explanation: '具体的な形や実体を持たず、抽象的な概念であること',
      },
      {
        kanji: '随所',
        kana: 'ずいしょ',
        explanation: 'あちこち、至る所',
      },
      {
        kanji: '卓越',
        kana: 'たくえつ',
        explanation: '優れていて、他を圧倒するほど傑出していること',
      },
      {
        kanji: '漠然',
        kana: 'ばくぜん',
        explanation: 'はっきりとした形や方向がなく、曖昧であること',
      },
      {
        kanji: '幻滅',
        kana: 'げんめつ',
        explanation: '期待や理想が破れ、失望すること',
      },
      {
        kanji: '堂々',
        kana: 'どうどう',
        explanation: '堂々とした様子。堂々とした振る舞い',
      },
      {
        kanji: '潔癖',
        kana: 'けっぺき',
        explanation: '清潔であることを非常に重要視すること',
      },
      {
        kanji: '偏在',
        kana: 'へんざい',
        explanation: '偏って存在すること。特定の場所や分野に集中すること',
      },
      {
        kanji: '静謐',
        kana: 'せいひつ',
        explanation: '静かで穏やかであり、平和な様子',
      },
      {
        kanji: '激怒',
        kana: 'げきど',
        explanation: '非常に激しく怒ること',
      },
      {
        kanji: '怨念',
        kana: 'おんねん',
        explanation: '過去の嫌な出来事などに対する強い怒りや恨み',
      },
      {
        kanji: '尊厳',
        kana: 'そんげん',
        explanation: '非常に尊重され、崇高であること',
      },
      {
        kanji: '憂慮',
        kana: 'ゆうりょ',
        explanation: '心配や懸念を感じること',
      },
      {
        kanji: '凌駕',
        kana: 'りょうが',
        explanation: '他をしのぐこと。超越すること',
      },
      {
        kanji: '快活',
        kana: 'かいかつ',
        explanation: '明るく元気で、楽しいさま',
      },
      {
        kanji: '端的',
        kana: 'たんてき',
        explanation: 'はっきりとしたさま。端正で明快な様子',
      },
      {
        kanji: '稚拙',
        kana: 'ちせつ',
        explanation: '未熟で幼稚な様子',
      },
      {
        kanji: '愉悦',
        kana: 'ゆえつ',
        explanation: '楽しみや喜びを感じること',
      },
      {
        kanji: '驚異',
        kana: 'きょうい',
        explanation: '驚くべき不可思議な出来事や力',
      },
      {
        kanji: '独裁',
        kana: 'どくさい',
        explanation: '一国や組織などを一人の指導者が独断で統治すること',
      },
      {
        kanji: '煩悩',
        kana: 'ぼんのう',
        explanation: '欲望や執着など、人を苦しめる心の乱れ',
      },
      {
        kanji: '混沌',
        kana: 'こんとん',
        explanation: '混乱や無秩序な状態',
      },
      {
        kanji: '雄大',
        kana: 'ゆうだい',
        explanation: '大きく力強いさま。壮大で荘厳な様子',
      },
      {
        kanji: '稀有',
        kana: 'けう',
        explanation: '非常に珍しく、希少であること',
      },
      {
        kanji: '漸次',
        kana: 'ぜんじ',
        explanation: '徐々に段階的に進むこと',
      },
      {
        kanji: '如実',
        kana: 'にょじつ',
        explanation: '実際の様子そのままであること',
      },
      {
        kanji: '飄々',
        kana: 'ひょうひょう',
        explanation: 'のんびりとして、物事に動じない様子',
      },
    ],
    // ------- 漢検2級 ------
    level2: [
      { kanji: '酪農', kana: 'らくのう', explanation: '乳製品を生産する農業のこと' },
      { kanji: '彙報', kana: 'いほう', explanation: '情報や資料をまとめて報告すること' },
      { kanji: '刹那', kana: 'せつな', explanation: '極めて短い時間。瞬間' },
      { kanji: '甚大', kana: 'じんだい', explanation: '非常に大きな程度。非常にひどいこと' },
      { kanji: '憤り', kana: 'いきどおり', explanation: '激しく怒ること。憤慨' },
      { kanji: '溺愛', kana: 'できあい', explanation: '過度に愛すること。過保護' },
      { kanji: '頻発', kana: 'ひんぱつ', explanation: '頻繁に発生すること' },
      { kanji: '尚早', kana: 'なおさはや', explanation: 'まだ時期尚早なこと。早計' },
      { kanji: '営繕', kana: 'えいぜん', explanation: '施設や建物を手入れし、管理すること' },
      { kanji: '悔悟', kana: 'かいご', explanation: '自分の過ちを深く悔い改めること' },
      { kanji: '瑕疵', kana: 'かし', explanation: '欠点や傷があること。不完全さ' },
      { kanji: '噴飯', kana: 'ふんぱん', explanation: '笑いすぎて食べ物が噴き出すこと。大笑い' },
      { kanji: '謳歌', kana: 'おうか', explanation: '歌って喜び誇ること。自由奔放な生き方' },
      { kanji: '複眼', kana: 'ふくがん', explanation: '昆虫などの目の構造で、複数の小さな眼から構成されていること' },
      { kanji: '凱旋', kana: 'がいせん', explanation: '戦勝の帰還。勝利をもって凱歌をあげて帰ること' },
      { kanji: '矜持', kana: 'きょうじ', explanation: '自尊心や誇り。自分の力量や美徳を保つ意志' },
      { kanji: '寓話', kana: 'ぐうわ', explanation: '教訓を含んだ物語。動物や物の言葉で表現される説話' },
      { kanji: '優雅', kana: 'ゆうが', explanation: '上品で優れた様子。優美で風雅なこと' },
      { kanji: '薫陶', kana: 'くんとう', explanation: '良い影響を与え、感化すること' },
      { kanji: '沁みる', kana: 'しみる', explanation: '心や感情に深く染み込む。心地よく感じられること' },
      { kanji: '深謀遠慮', kana: 'しんぼうえんりょ', explanation: '深く考え、将来にわたって慎重に計画すること' },
      { kanji: '躾', kana: 'しつけ', explanation: '礼儀や規則を身につけさせること。しつけること' },
      { kanji: '鼓膜', kana: 'こまく', explanation: '耳の中にある薄い膜。音を感知する役割がある' },
      { kanji: '謙虚', kana: 'けんきょ', explanation: '自分を過小評価し、相手を尊重する態度' },
      { kanji: '鶴翼', kana: 'かくよく', explanation: '二つの者が協力して優れた結果を生むこと' },
      { kanji: '縁起', kana: 'えんぎ', explanation: '良い運気や幸運の兆し' },
      {
        kanji: '優柔不断',
        kana: 'ゆうじゅうふだん',
        explanation: '優れた選択をすることができず、悩んで決断できないこと',
      },
      { kanji: '諧謔', kana: 'かいぎゃく', explanation: 'おかしみやユーモアのあること' },
      { kanji: '懐古', kana: 'かいこ', explanation: '昔のことを懐かしく思い返すこと' },
      { kanji: '偲念', kana: 'しのび', explanation: '故人や過去の出来事を思い起こし、思いやること' },
      { kanji: '篤実', kana: 'とくじつ', explanation: '真面目で誠実な態度や性格' },
      { kanji: '微睡', kana: 'びすい', explanation: 'かすかに目を閉じている状態。微細な睡眠' },
      { kanji: '艶麗', kana: 'えんれい', explanation: '美しさや優雅さが魅力的であること' },
      { kanji: '雅致', kana: 'がち', explanation: '上品で趣があり、美しい感じ' },
      { kanji: '奢靡', kana: 'しゃび', explanation: '贅沢で豪華な様子。けちなくらい贅を尽くすこと' },
      { kanji: '陶酔', kana: 'とうすい', explanation: '非常に幸福で興奮している様子' },
      { kanji: '綻びる', kana: 'ほころびる', explanation: '少しずつ開く様子。優れたものが顕在すること' },
      { kanji: '咄嗟', kana: 'とっさ', explanation: 'その場の状況に応じて即座に行動すること' },
      { kanji: '瑠璃', kana: 'るり', explanation: '透明で美しい青色や緑色の宝石' },
      { kanji: '翻弄', kana: 'ほんろう', explanation: '思いのままに操ること。あれこれと遊ぶこと' },
      { kanji: '潔癖', kana: 'けっぺき', explanation: '非常に清潔で物に対して潔癖なこと' },
      { kanji: '愧赧', kana: 'きたん', explanation: '自分の過ちや恥ずかしいことを感じて顔が赤らむこと' },
      { kanji: '肆意', kana: 'しい', explanation: '思うままに振る舞うこと。自由奔放な態度' },
      { kanji: '悠揚', kana: 'ゆうよう', explanation: 'のんびりとした様子。穏やかでゆったりとした感じ' },
      { kanji: '奇巧', kana: 'きこう', explanation: '非常に独創的で巧妙なこと。奇抜で精巧なもの' },
      { kanji: '蓋然', kana: 'がいぜん', explanation: '非常にありそうなこと。起こりそうな確率が高いこと' },
      { kanji: '殊勝', kana: 'しゅしょう', explanation: '非常に優れていて素晴らしいこと' },
      { kanji: '愚直', kana: 'ぐちょく', explanation: '愚かで素直な態度や性格' },
      { kanji: '粛然', kana: 'しゅくぜん', explanation: '肅然としていて、厳かな様子' },
      { kanji: '静謐', kana: 'せいひつ', explanation: '非常に静かで穏やかな様子' },
      { kanji: '禍根', kana: 'かこん', explanation: '災いや害悪の原因や根源' },
      { kanji: '蕩漾', kana: 'とうよう', explanation: '心が蕩けるように揺れ動くこと' },
      { kanji: '凜然', kana: 'りんぜん', explanation: '威厳があり、冷徹で力強い様子' },
      { kanji: '潤沢', kana: 'じゅんたく', explanation: '豊富で十分な様子' },
      { kanji: '耶蘇', kana: 'やす', explanation: 'キリスト教でイエス・キリストのこと' },
      { kanji: '懐疑', kana: 'かいぎ', explanation: '疑念を抱くこと。疑うこと' },
      { kanji: '謹厳', kana: 'きんげん', explanation: '非常に厳格で慎み深い様子' },
      { kanji: '粋炸', kana: 'いきざつ', explanation: '粋で華やかな様子' },
      { kanji: '澄明', kana: 'ちょうめい', explanation: '非常に澄んで明るい様子' },
      { kanji: '戚戚', kana: 'せきせき', explanation: '寂しくて心細い様子' },
      { kanji: '蕩然', kana: 'とうぜん', explanation: '心が蕩けるように優美で美しい様子' },
      { kanji: '憂愁', kana: 'ゆうしゅう', explanation: '悲しみや苦しみに満ちた様子' },
      { kanji: '孤高', kana: 'ここう', explanation: '一人でいることを好み、高潔で優れた様子' },
      { kanji: '颯爽', kana: 'さっそう', explanation: 'さっぱりとして爽やかで清々しい様子' },
      { kanji: '鬱憤', kana: 'うっぷん', explanation: '悔しさや怒りが積もり積もった様子' },
      { kanji: '剛健', kana: 'ごうけん', explanation: '非常に強くて丈夫な様子' },
      { kanji: '豁達', kana: 'かくたつ', explanation: '物事に対して深く考えず、開かれた様子' },
      { kanji: '横恋慕', kana: 'おうれんぼ', explanation: '既婚者が他の異性に対して恋慕の情を抱くこと' },
      { kanji: '習気', kana: 'しゅうき', explanation: '日常の風景や事物が身近で馴染み深い様子' },
      { kanji: '鮮活', kana: 'せんかつ', explanation: '非常に新鮮で生き生きとした様子' },
      { kanji: '奇遇', kana: 'きぐう', explanation: '予測できない偶然の出会いや状況' },
      { kanji: '華やか', kana: 'はなやか', explanation: '美しく洗練されていて華やかな様子' },
      { kanji: '宵闇', kana: 'よいやみ', explanation: '夕方から夜にかけての薄明かりがかかった様子' },
      { kanji: '瑞々しい', kana: 'みずみずしい', explanation: '生命力に満ち、新鮮でみずみずしい様子' },
      { kanji: '風流', kana: 'ふうりゅう', explanation: '雅致があり、趣がある様子' },
      { kanji: '純真', kana: 'じゅんしん', explanation: '清らかで偽りのない様子' },
      { kanji: '悠久', kana: 'ゆうきゅう', explanation: '永遠に続くかのように長い様子' },
      { kanji: '彩り豊か', kana: 'いろどりゆたか', explanation: '多彩で美しく、鮮やかな様子' },
      { kanji: '温順', kana: 'おんしゅん', explanation: '温和でおとなしい様子' },
      { kanji: '清楚', kana: 'せいそ', explanation: '清潔で上品であり、淑やかな様子' },
      { kanji: '愉悦', kana: 'ゆえつ', explanation: '楽しみや喜びに満ちた様子' },
      { kanji: '愛らしい', kana: 'あいらしい', explanation: '愛嬌があり、可愛らしい様子' },
      { kanji: '無邪気', kana: 'むじゃき', explanation: '悪意や偽りのない純真な様子' },
      { kanji: '優雅', kana: 'ゆうが', explanation: '上品で気品があり、優れた様子' },
      { kanji: '奥ゆかしい', kana: 'おくゆかしい', explanation: '控えめで内面に深みがある様子' },
      { kanji: '緻密', kana: 'ちみつ', explanation: '細かい部分まできめ細やかで丁寧な様子' },
      { kanji: '慈愛', kana: 'じあい', explanation: '深い愛情や思いやりがある様子' },
      { kanji: '逞しい', kana: 'たくましい', explanation: '強くて頼りになる様子' },
      { kanji: '躍動感', kana: 'やくどうかん', explanation: '活気に満ち、元気な様子' },
      { kanji: '悠然', kana: 'ゆうぜん', explanation: 'のんびりとして余裕があり、穏やかな様子' },
      { kanji: '潤色', kana: 'じゅんしょく', explanation: '美しさが潤いを帯びた様子' },
      { kanji: '軽快', kana: 'けいかい', explanation: '軽やかで快活な様子' },
      { kanji: '艶麗', kana: 'えんれい', explanation: '美しさや優雅さが艶やかで豊かな様子' },
      { kanji: '奇異', kana: 'きい', explanation: '普通でなく、異常な様子' },
      { kanji: '威厳', kana: 'いげん', explanation: '威力や重厳があり、厳かな様子' },
      { kanji: '神秘', kana: 'しんぴ', explanation: '不可思議で神聖な様子' },
      { kanji: '綺麗', kana: 'きれい', explanation: '美しさや清潔感がある様子' },
      { kanji: '芳醇', kana: 'ほうじゅん', explanation: '香りが濃く、豊かな様子' },
      { kanji: '粛然', kana: 'しゅくぜん', explanation: '肃然としていて、厳かな様子' },
      { kanji: '悠々', kana: 'ゆうゆう', explanation: 'のんびりとして余裕があり、穏やかな様子' },
      { kanji: '淡白', kana: 'たんぱく', explanation: '控えめで色気のない様子' },
      { kanji: '稜角', kana: 'りょうかく', explanation: '鋭い角や隅がくっきりとした様子' },
      { kanji: '悠久', kana: 'ゆうきゅう', explanation: '永遠に続くかのように長い様子' },
      { kanji: '玲瓏', kana: 'れいろう', explanation: '美しさや透明感があり、輝く様子' },
      { kanji: '揶揄', kana: 'やゆ', explanation: 'からかったり冗談を言ったりする様子' },
      { kanji: '翳り無い', kana: 'かげりない', explanation: '欠点や汚れが一切ない様子' },
      { kanji: '喜捨', kana: 'きしゃ', explanation: '喜んで物を施すこと' },
      { kanji: '悠揚', kana: 'ゆうよう', explanation: '心地よい音や風が響いている様子' },
      { kanji: '澄明', kana: 'ちょうめい', explanation: '非常に澄んで明るい様子' },
      { kanji: '堂々', kana: 'どうどう', explanation: '威厳があり、堂々とした様子' },
      { kanji: '実直', kana: 'じっちょく', explanation: '正直で実直な態度や性格' },
      { kanji: '巧妙', kana: 'こうみょう', explanation: '非常に巧みで緻密な様子' },
      { kanji: '慈悲深い', kana: 'じひぶかい', explanation: '深い慈悲の心を持っている様子' },
      { kanji: '瑰奇', kana: 'かいき', explanation: '美しさや独特さが非常に際立っている様子' },
      { kanji: '粋炸', kana: 'いきざつ', explanation: '粋で華やかな様子' },
      { kanji: '情熱的', kana: 'じょうねつてき', explanation: '非常に熱心で情熱的な様子' },
      { kanji: '悠然', kana: 'ゆうぜん', explanation: 'のんびりとして余裕があり、穏やかな様子' },
      { kanji: '勇壮', kana: 'ゆうそう', explanation: '非常に勇ましく、力強い様子' },
      { kanji: '華美', kana: 'かび', explanation: '非常に派手で華やかな様子' },
      { kanji: '艶麗', kana: 'えんれい', explanation: '美しさや優雅さが艶やかで豊かな様子' },
      { kanji: '静謐', kana: 'せいひつ', explanation: '非常に静かで穏やかな様子' },
      { kanji: '愉快', kana: 'ゆかい', explanation: '楽しくて愉快な様子' },
      { kanji: '可憐', kana: 'かれん', explanation: '愛らしさや優美さがある様子' },
      { kanji: '颯爽', kana: 'さっそう', explanation: 'さっぱりとして爽やかで清々しい様子' },
      { kanji: '神聖', kana: 'しんせい', explanation: '崇高で神聖な様子' },
      { kanji: '激昂', kana: 'げきこう', explanation: '激しく怒る様子' },
      { kanji: '逍遥', kana: 'しょうよう', explanation: 'のんびりと気ままに動き回る様子' },
      { kanji: '謙虚', kana: 'けんきょ', explanation: '謙遜で控えめな態度や性格' },
      { kanji: '麗しい', kana: 'うるわしい', explanation: '美しさがある様子' },
      { kanji: '奇巧', kana: 'きこう', explanation: '非常に奇抜で巧妙な様子' },
      { kanji: '妖艶', kana: 'ようえん', explanation: '妖しさがあり、艶やかな様子' },
      { kanji: '破天荒', kana: 'はてんこう', explanation: '世間一般の常識にとらわれない様子' },
      { kanji: '慈愛に満ちた', kana: 'じあいにみちた', explanation: '深い愛情や思いやりが満ちている様子' },
      { kanji: '機敏', kana: 'きびん', explanation: '物事に敏感で素早い様子' },
      { kanji: '瑞々しい', kana: 'みずみずしい', explanation: '生命力に満ち、新鮮でみずみずしい様子' },
      { kanji: '躍動', kana: 'やくどう', explanation: '活気に満ち、元気な様子' },
      { kanji: '情熱', kana: 'じょうねつ', explanation: '非常に熱心で情熱的な様子' },
      { kanji: '瀟洒', kana: 'しょうしゃ', explanation: '洗練されておしゃれで清潔な様子' },
      { kanji: '端麗', kana: 'たんれい', explanation: '清楚で美しい様子' },
      { kanji: '奇異', kana: 'きい', explanation: '普通でなく、異常な様子' },
      { kanji: '優雅', kana: 'ゆうが', explanation: '上品で気品があり、優れた様子' },
      { kanji: '陶酔', kana: 'とうすい', explanation: '非常に感動し、心を奪われる様子' },
      { kanji: '深淵', kana: 'しんえん', explanation: '深くて底知れぬ様子' },
      { kanji: '憧憬', kana: 'しょうけい', explanation: '憧れや憬れの念がある様子' },
      { kanji: '緻密', kana: 'ちみつ', explanation: '細かい部分まできめ細やかで丁寧な様子' },
      { kanji: '懐疑的', kana: 'かいぎてき', explanation: '疑念や不信感を抱いている様子' },
      { kanji: '偉容', kana: 'いよう', explanation: '威厳があり、堂々とした様子' },
      { kanji: '気品', kana: 'きひん', explanation: '上品で気高い様子' },
      { kanji: '花鳥風月', kana: 'かちょうふうげつ', explanation: '自然や美を愛でる様子' },
    ],
    //  ------- 漢検1級 ------
    level3: [
      { kanji: '蹉跌', kana: 'さてつ', explanation: 'つます、つまずくこと' },
      { kanji: '錚錚', kana: 'そうそう', explanation: '音が鳴り響くさま' },
      { kanji: '霍乱', kana: 'かくらん', explanation: '急性で流行する伝染病' },
      { kanji: '明礬', kana: 'めいばん', explanation: '鉱石の一種で、止血や消臭に用いる' },
      { kanji: '炬燵', kana: 'こたつ', explanation: '炭火を入れた暖房器具' },
      { kanji: '梵唄', kana: 'ぼんぱい', explanation: '仏教の歌や音楽' },
      { kanji: '荼毘', kana: 'たび', explanation: '死者を火葬すること' },
      { kanji: '痙攣', kana: 'けいれん', explanation: '筋肉が勝手に収縮すること' },
      { kanji: '馮河', kana: 'ひょうが', explanation: '川の氾濫や氾濫した川' },
      { kanji: '嚆矢', kana: 'こうし', explanation: '物事のはじまりや原因' },
      { kanji: '褥瘡', kana: 'じょくそう', explanation: '寝たきりなどでできる床ずれ' },
      { kanji: '婉娩', kana: 'えんべん', explanation: '優雅で美しいこと' },
      { kanji: '霄壌', kana: 'しょうじょう', explanation: '天空と大地、広大な範囲' },
      { kanji: '罨法', kana: 'えんぽう', explanation: '仏像や彫刻などに墨を塗る技法' },
      { kanji: '腱鞘', kana: 'けんしょう', explanation: '腱を包み込む袋状の組織' },
      { kanji: '静謐', kana: 'せいひつ', explanation: '静かで穏やかな様子' },
      { kanji: '跋扈', kana: 'ばっこ', explanation: '思うままに振る舞うこと' },
      { kanji: '鍼灸', kana: 'しんきゅう', explanation: '鍼と灸を用いた東洋医学の一環' },
      { kanji: '雷霆', kana: 'らいてい', explanation: '雷の轟音や雷鳴' },
      { kanji: '鶺鴒', kana: 'せきれい', explanation: '鳥の名前。サンコウチョウ' },
      { kanji: '忸怩', kana: 'じくじ', explanation: 'たじたじしいさま、気まずさ' },
      { kanji: '拈華', kana: 'ねんげ', explanation: '手で花を摘むこと。手で花を取ること' },
      { kanji: '逡巡', kana: 'しゅんじゅん', explanation: 'ためらい迷うこと' },
      { kanji: '真鍮', kana: 'しんちゅう', explanation: '銅と亜鉛を合わせた合金でできた金属' },
      { kanji: '慙愧', kana: 'ざんき', explanation: '恥じ入ること、恥ずかしさ' },
      { kanji: '駱駝', kana: 'らくだ', explanation: '草食性の動物で、背中にたくさんのこぶがある' },
      { kanji: '惨憺', kana: 'さんたん', explanation: 'ひどく荒れ果てているさま' },
      { kanji: '痼疾', kana: 'こしつ', explanation: '慢性的で重い病気' },
      { kanji: '逍遥', kana: 'しょうよう', explanation: '自由でのんびりとした様子' },
      { kanji: '蜿蜒', kana: 'えんえん', explanation: 'くねくねと曲がりくねる様子' },
      { kanji: '喀痰', kana: 'かくたん', explanation: '咳やたんからを吐き出すこと' },
      { kanji: '駘蕩', kana: 'たいとう', explanation: '馬が蕩けるように疲れていること' },
      { kanji: '潺湲', kana: 'せんえん', explanation: '川の流れる音' },
      { kanji: '不逞', kana: 'ふてい', explanation: '礼儀知らずで行儀の悪いこと' },
      { kanji: '瀟灑', kana: 'しょうさつ', explanation: 'さっぱりとして清らかな様子' },
      { kanji: '謦咳', kana: 'けいがい', explanation: 'のどを鳴らすような咳' },
      { kanji: '剪刀', kana: 'はさみ', explanation: '紙や布などを切るための道具' },
      { kanji: '掉尾', kana: 'とうび', explanation: '言葉や文章の末尾が下がること' },
      { kanji: '叮嚀', kana: 'ていちょう', explanation: '小言や注意' },
      { kanji: '襤褸', kana: 'らんる', explanation: '古くなって破れた布地や衣類' },
      { kanji: '爛熟', kana: 'らんじゅく', explanation: '十分に熟して柔らかいこと' },
      { kanji: '流謫', kana: 'りゅうちゃく', explanation: '故郷を追放されて他の地に住むこと' },
      { kanji: '均霑', kana: 'きんせん', explanation: '平らで均一に湿ること' },
      { kanji: '蜉蝣', kana: 'かげろう', explanation: 'トンボの俳称' },
      { kanji: '炊爨', kana: 'すいさん', explanation: '料理を作ること' },
      { kanji: '結紮', kana: 'けっさつ', explanation: '血管や組織を締めて結ぶこと' },
      { kanji: '証憑', kana: 'しょうひょう', explanation: '事実を証明する根拠や証拠' },
      { kanji: '千仞', kana: 'せんじん', explanation: '深さが千丈あること' },
      { kanji: '挂冠', kana: 'かかん', explanation: '一時の成功や名声を手に入れること' },
      { kanji: '憔悴', kana: 'しょうすい', explanation: 'やつれてみすぼらしい様子' },
      { kanji: '鏤刻', kana: 'ろうこく', explanation: '彫り物を施すこと' },
      { kanji: '霊柩', kana: 'れいきゅう', explanation: '死者の遺体を安置して運ぶ棺' },
      { kanji: '騏驥', kana: 'きき', explanation: '優れた馬のたとえ。千里を走る優れた馬' },
      { kanji: '脚絆', kana: 'あしはだ', explanation: '足首を結ぶ紐。足枷' },
      { kanji: '浚渫', kana: 'しゅんせつ', explanation: '堆積物や沈泥を取り除くこと' },
      { kanji: '服膺', kana: 'ふくよう', explanation: '心から理解し、身に受けること' },
      { kanji: '霹靂', kana: 'へきれき', explanation: '雷鳴や雷光' },
      { kanji: '瀰漫', kana: 'びまん', explanation: '広く行き渡り、ある物がある場所を満たす様子' },
      { kanji: '焙煎', kana: 'ばいせん', explanation: '野菜や豆などを焼いて香ばしくすること' },
      { kanji: '蹂躪', kana: 'じゅうりん', explanation: '踏みにじること。軽蔑して踏みにじること' },
      { kanji: '刮目', kana: 'かつもく', explanation: '感心して驚くこと' },
      { kanji: '剴切', kana: 'がいせつ', explanation: '利口で機敏なこと' },
      { kanji: '膺懲', kana: 'えいちょう', explanation: '戒めを心に受け、改めること' },
      { kanji: '哄笑', kana: 'こうしょう', explanation: '大勢で笑い騒ぐこと' },
      { kanji: '喀血', kana: 'かくけつ', explanation: '血を吐くこと' },
      { kanji: '縲絏', kana: 'るいけつ', explanation: '縄で結んだり細く細工すること' },
      { kanji: '靄靄', kana: 'あいあい', explanation: '霧や煙が充満している様子' },
      { kanji: '嚥下', kana: 'えんげ', explanation: '飲み込むこと' },
      { kanji: '靉靆', kana: 'あいたく', explanation: '天気が崩れて曇り、雨や雪が降る様子' },
      { kanji: '屛風', kana: 'びょうぶ', explanation: '風除けや日よけとして使う、屏風の一種' },
      { kanji: '譴責', kana: 'けんせき', explanation: '非難や責めること' },
      { kanji: '旗帜', kana: 'きし', explanation: '旗のしるし。標語や信念' },
      { kanji: '恫喝', kana: 'どうかつ', explanation: '強い口調でおどし、脅すこと' },
      { kanji: '危惧', kana: 'きぐ', explanation: '心配して恐れること' },
      { kanji: '崑崙', kana: 'こんろん', explanation: '中国の西方にある山の名前。比喩的には高く大きなこと' },
      { kanji: '鷸蚌', kana: 'いしきり', explanation: '争いごとのこと。争いの原因' },
      { kanji: '扼腕', kana: 'やくわん', explanation: '腕を握って抑えること。力強く意気込むこと' },
      { kanji: '穹窿', kana: 'きゅうろう', explanation: '空が高く広がっている様子' },
      { kanji: '朦朧', kana: 'もうろう', explanation: 'はっきりしない様子。ぼんやりしていること' },
      { kanji: '矍鑠', kana: 'かくしゃく', explanation: '目が鋭く見る様子。活発で勇ましいこと' },
      { kanji: '桎梏', kana: 'しっこく', explanation: '自由を束縛するもの。拘束や制約' },
      { kanji: '脚気', kana: 'きゃっき', explanation: 'ビタミンB1不足により起こる病気。むくみや足の痛みが特徴' },
      { kanji: '奢侈', kana: 'しゃし', explanation: '贅沢で豪華なこと。無駄に贅沢なこと' },
      { kanji: '偃蹇', kana: 'えんけん', explanation: '物事が停滞し、進まないこと' },
      { kanji: '窈窕', kana: 'ようちょう', explanation: '美しい姿勢や容姿。控えめで優雅な様子' },
      { kanji: '肯綮', kana: 'こうけい', explanation: '賛成すること。応じること' },
      { kanji: '巫覡', kana: 'ふぎ', explanation: '巫女や占い師のこと。巫女として神聖な儀式を行う女性' },
      { kanji: '急遽', kana: 'きゅうきょ', explanation: '急に、突然' },
      { kanji: '狒狒', kana: 'ひひ', explanation: '猿の一種。大きな猿のこと' },
      { kanji: '喇叭', kana: 'ラッパ', explanation: 'ラッパやトランペットのこと。大声で叫ぶこと' },
      { kanji: '咨嗟', kana: 'しさ', explanation: '相談や忠告。物事について尋ねること' },
      { kanji: '脳漿', kana: 'のうしょう', explanation: '脳の中の液体。比喩的には頭脳の中の知識や思考' },
      { kanji: '嚠喨', kana: 'りゅうりょう', explanation: '風が強く吹き荒れる様子' },
      { kanji: '邁進', kana: 'まいしん', explanation: '勢いを増して進むこと。精力的に前進すること' },
      { kanji: '蒟蒻', kana: 'こんにゃく', explanation: 'こんにゃく芋から作られる食品。食物繊維が豊富' },
      { kanji: '顰蹙', kana: 'ひんしゅく', explanation: '顔をしかめて不快な様子。非難や反発' },
      { kanji: '徘徊', kana: 'はいかい', explanation: 'あちこち歩き回ること。気まぐれな動き' },
      { kanji: '稀覯', kana: 'きこう', explanation: '珍しくて貴重なこと' },
      { kanji: '怜悧', kana: 'れいり', explanation: '賢くて悩ましいこと' },
      { kanji: '幽邃', kana: 'ゆうすい', explanation: '深くて静かで神秘的なこと' },
    ],
  };
}
